### ISSUE TITLE
Error in dt_pivot_wider()

### ISSUE THREAD

**Issue by markfairbanks** [TysonStanley/tidyfast#16]
I found a small error in dt_pivot_wider().
This part:
```r
} else if (length(id_cols == 1)) {
```
Should instead be:
```r
} else if (length(id_cols) == 1) {
```

**Comment by TysonStanley** [comment]
Good catch. Thanks for pointing me to that. Turns out that your final else statement works with `length(id_cols) == 1` and `length(id_cols) > 1` so I just removed it. This is because `paste(id_cols, collapse = " + ")` will just print the single column if there is just one or will print multiple separated by + if there is more :)

**Comment by TysonStanley** [comment]
@mtfairbanks quick question. Wanted to add you to the DESCRIPTION file as a contributor for your great addition to `tidyfast`. Is there a name you'd like for me to put on there?

**Comment by markfairbanks** [comment]
@TysonStanley - that sounds great. My name’s Mark Fairbanks
