### ISSUE TITLE
Seamless handoff to `dtplyr`

### ISSUE THREAD

**Issue by vincentarelbundock** [TysonStanley/tidyfast#33]
I feel like it would be a good idea to support something like this:

```
library(dtplyr)
library(tidyfast)

data.frame(
   x = rnorm(1e5),
   y = runif(1e5),
   grp = sample(1L:5L, 1e5, replace = TRUE)) %>%
   lazy_dt %>%
   dt_pivot_longer(-grp)
```

Right now, `dt_pivot_longer` et al. only accept `data.frame` or `data.table`. But if you could support `dtplyr_step` objects, then there would be a *very* powerful use-case for all of the `tidyfast` functions. They could be plugged in to a `dtplyr` workflow to fill-in the unsupported functions.

One possible design would be to create S3 methods for each of your functions for `dtplyr_step`. Those methods would simply "collect" the result of previous computation with `as.data.table`, run the method associated with `data.table` objects, and wrap the output in a `lazy_dt()` call.

I image each method could be <5 lines of code, for a tremendous added value.

Let me know what you think. I'd be happy to help start a PR if this is something you're genuinely interested in.

**Comment by TysonStanley** [comment]
I LOVE this idea. I've been hesitant to go there, just because I'd need to get more into the mechanics of `dtplyr` but I think you are definitely right and `dtplyr` is something I wanted to dive into more. From my glances at the code, really it is just creating an unevaluated expression of `data.table` syntax. 

I think there are two possible directions we could go with this:

1. Do as you suggest--running the as.data.table() to collect the results up to that point, run the default version of the function, and then return a lazy_dt() object. I think this is the most straightforward approach.
2. Integrate the function into the unevaluated call. This one is more complex and may not have many advantages because many of the calls will not be able to be seamlessly added to the unevaluated call. For example, `dt_pivot_longer()` calls `melt.data.table()` under the hood, which would be difficult to combine with the rest of the unevaluated call, although it would probably be possible. However, true integration into the unevaluated call can help the process be more seamless and integrated.

For now, I think the first (your idea) is our best bet. I think a push from you is all I need to get going with this. Would you be willing to start a PR? I can add you as a contributor to `tidyfast`, if you'd like.

**Comment by vincentarelbundock** [comment]
Sounds great. I'll do some initial tests and open a PR with proof of concept code. Then we can see how to proceed from there.

**Comment by vincentarelbundock** [comment]
Quick question about NSE (about which I am not an expert). An easy way to implement this would be to call `dt_pivot_longer.default` from inside `dt_pivot_longer.dtplyr_step` (after conversion to `data.table`). In that context, what would be your preferred way to pass `cols` down from the `dtplyr_step` method to the `default` method?

Normally, I would use the `{{}}` embrace, but it doesn't seem to work with how you've set up `substitute` et al.:


``` r
library(tidyfast)
library(tidyr)
library(rlang)

wrapper <- function(x, cols) {
  pivot_longer(x, {{cols}})
}

fwrapper <- function(x, cols) {
  dt_pivot_longer(dat, {{cols}})
}


dat <- data.frame(x=1:2, y=2:3, z=3:4)
wrapper(dat, c(x, y))
#> # A tibble: 4 x 3
#>       z name  value
#>   <int> <chr> <int>
#> 1     3 x         1
#> 2     3 y         2
#> 3     4 x         2
#> 4     4 y         3

fwrapper(dat, c(x, y))
#> Error in eval(select_vars, data_vars): object 'cols' not found

wrapper(dat, -x)
#> # A tibble: 4 x 3
#>       x name  value
#>   <int> <chr> <int>
#> 1     1 y         2
#> 2     1 z         3
#> 3     2 y         3
#> 4     2 z         4

fwrapper(dat, -x)
#> Error in eval(select_vars, data_vars): object 'cols' not found
```

<sup>Created on 2020-08-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by TysonStanley** [comment]
Great question. In this case, instead of `{{cols}}`, you can do `eval(substitute(cols))`. It is similar (although not identical) in what it is trying to do.

**Comment by vincentarelbundock** [comment]
Hmmm, but then I get:

``` r
library(tidyfast)
dat <- data.frame(x=1:2, y=2:3, z=3:4)
fwrapper <- function(x, cols) {
  dt_pivot_longer(dat, eval(substitute(cols)))
}
fwrapper(dat, -x)
#> Error in eval(substitute(cols)): object 'cols' not found
```

<sup>Created on 2020-08-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by vincentarelbundock** [comment]
TBC, I can just copy over the same code you have in `.default` to the new method. A working version of the minimal example in my previous post would just allow me to save some code duplication.

**Comment by TysonStanley** [comment]
Yes, I see what is happening. Sorry, I didn't think it through that you'd be passing that information... It actually looks like it is best if you substitute and eval the whole expression, not just the cols. Try this:

```r
fwrapper <- function(x, cols) {
  expr = substitute(dt_pivot_longer(x, cols))
  eval(expr)
}
```

**Comment by TysonStanley** [comment]
Closing this issue because `dtplyr` has implemented many of the function in `tidyfast` so unlikely to be worth connecting the two. I think if someone is using `tidyfast` at this point, it's partly because of the low overhead and would probably not be using `dtplyr`.
